name: GeneExprRegBySTR
channels:
- conda-forge
- bioconda
- pytorch
- defaults

dependencies:
- python
- numpy
- pandas
- pyarrow
- pytorch::pytorch
- pytorch::cpuonly
- biopython
- bedtools=2.30.0
- samtools
- pyjaspar
- matplotlib
- seaborn
- homer
- beautifulsoup4
- lxml