name: GeneExprRegBySTR
channels:
- conda-forge
- bioconda
- defaults

dependencies:
- python
- numpy
- pandas
- pyarrow
- pytorch 
- biopython
- bedtools=2.30.0
- samtools
- pyjaspar
- matplotlib
- seaborn
- homer
- beautifulsoup4 
- lxml 